import Stripe from 'stripe';

const GHL_API_KEY = process.env.GHL_API_KEY;
const GHL_LOCATION_ID = 'cbDr5Xe384SCZnhPMvuZ';
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET;

export const config = {
  api: {
      bodyParser: false,
        },
        };

        async function getRawBody(req) {
          return new Promise((resolve, reject) => {
              const chunks = [];
                  req.on('data', chunk => chunks.push(chunk));
                      req.on('end', () => resolve(Buffer.concat(chunks)));
                          req.on('error', reject);
                            });
                            }

                            async function findGHLContact(email) {
                              const res = await fetch(
                                  `https://services.leadconnectorhq.com/contacts/?locationId=${GHL_LOCATION_ID}&email=${encodeURIComponent(email)}`,
                                      {
                                            headers: {
                                                    'Authorization': 'Bearer ' + GHL_API_KEY,
                                                            'Version': '2021-07-28',
                                                                  },
                                                                      }
                                                                        );
                                                                          const data = await res.json();
                                                                            const contacts = data.contacts || [];
                                                                              if (contacts.length === 0) return null;
                                                                                return contacts[0];
                                                                                }

                                                                                async function applyGHLTag(contactId, tag) {
                                                                                  const res = await fetch(
                                                                                      `https://services.leadconnectorhq.com/contacts/${contactId}/tags`,
                                                                                          {
                                                                                                method: 'POST',
                                                                                                      headers: {
                                                                                                              'Authorization': 'Bearer ' + GHL_API_KEY,
                                                                                                                      'Version': '2021-07-28',
                                                                                                                              'Content-Type': 'application/json',
                                                                                                                                    },
                                                                                                                                          body: JSON.stringify({ tags: [tag] }),
                                                                                                                                              }
                                                                                                                                                );
                                                                                                                                                  const data = await res.json();
                                                                                                                                                    console.log(`Tag "${tag}" applied to ${contactId}: status ${res.status}`);
                                                                                                                                                      return data;
                                                                                                                                                      }
                                                                                                                                                      
                                                                                                                                                      async function createGHLContact(email, name) {
                                                                                                                                                        const [firstName, ...rest] = (name || '').split(' ');
                                                                                                                                                          const res = await fetch(
                                                                                                                                                              'https://services.leadconnectorhq.com/contacts/',
                                                                                                                                                                  {
                                                                                                                                                                        method: 'POST',
                                                                                                                                                                              headers: {
                                                                                                                                                                                      'Authorization': 'Bearer ' + GHL_API_KEY,
                                                                                                                                                                                              'Version': '2021-07-28',
                                                                                                                                                                                                      'Content-Type': 'application/json',
                                                                                                                                                                                                            },
                                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                                          locationId: GHL_LOCATION_ID,
                                                                                                                                                                                                                                  firstName: firstName || '',
                                                                                                                                                                                                                                          lastName: rest.join(' ') || '',
                                                                                                                                                                                                                                                  email: email,
                                                                                                                                                                                                                                                          source: 'Stripe Direct Payment',
                                                                                                                                                                                                                                                                  tags: ['deep-audit-paid'],
                                                                                                                                                                                                                                                                        }),
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                const data = await res.json();
                                                                                                                                                                                                                                                                                  console.log(`Created new GHL contact for ${email}: status ${res.status}`);
                                                                                                                                                                                                                                                                                    return data.contact || null;
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                    export default async function handler(req, res) {
                                                                                                                                                                                                                                                                                      if (req.method === 'OPTIONS') return res.status(200).end();
                                                                                                                                                                                                                                                                                        if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                          const rawBody = await getRawBody(req);
                                                                                                                                                                                                                                                                                            const sig = req.headers['stripe-signature'];
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                              let event;
                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2023-10-16' });
                                                                                                                                                                                                                                                                                                        event = stripe.webhooks.constructEvent(rawBody, sig, STRIPE_WEBHOOK_SECRET);
                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                              console.error('Stripe signature verification failed:', err.message);
                                                                                                                                                                                                                                                                                                                  return res.status(400).json({ error: `Webhook error: ${err.message}` });
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                      if (event.type === 'checkout.session.completed') {
                                                                                                                                                                                                                                                                                                                          const session = event.data.object;
                                                                                                                                                                                                                                                                                                                              const email = session.customer_details?.email || session.customer_email;
                                                                                                                                                                                                                                                                                                                                  const name = session.customer_details?.name || '';
                                                                                                                                                                                                                                                                                                                                      const amountPaid = session.amount_total; // cents
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                          console.log(`checkout.session.completed: email=${email} amount=${amountPaid}`);
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                              if (!email) {
                                                                                                                                                                                                                                                                                                                                                    console.error('No email in Stripe session — cannot tag in GHL');
                                                                                                                                                                                                                                                                                                                                                          return res.status(200).json({ received: true, warning: 'no_email' });
                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                        let contact = await findGHLContact(email);
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                              if (!contact) {
                                                                                                                                                                                                                                                                                                                                                                                      // Edge case: paid directly without going through the snapshot form first
                                                                                                                                                                                                                                                                                                                                                                                              console.log(`No existing GHL contact for ${email} — creating one`);
                                                                                                                                                                                                                                                                                                                                                                                                      contact = await createGHLContact(email, name);
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                  if (contact) {
                                                                                                                                                                                                                                                                                                                                                                                                                          await applyGHLTag(contact.id, 'deep-audit-paid');
                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(`Successfully processed payment for contact ${contact.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error('GHL processing error:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Always return 200 to Stripe — prevents Stripe from retrying on GHL errors
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(200).json({ received: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
